# Generated by Django 3.0.7 on 2020-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_name', models.CharField(max_length=60)),
                ('stock', models.IntegerField(max_length=60)),
                ('selling_price', models.FloatField(max_length=60)),
                ('cost_price', models.FloatField(max_length=60)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
