# Generated by Django 3.0.5 on 2020-12-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_portal_api', '0002_auto_20201225_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
